### PR TITLE
Added typescript typings

### PR DESCRIPTION
**Pull request by OctoD**
For ts users.

### CODE REVIEW

**Comment by ai** [comment]
`@author    {ashelley <andrey@sitnik.ru>}`— seems like wrong :)

**Comment by ai** [comment]
Also did you mention all options in this type definition? I can’t find `silent` and `unknown` there.

**Comment by ai** [comment]
Thanks. Released in 3.1.0.

**Comment by OctoD** [comment]
Thanks to you for your work :smile:

**Pull request merged**
