### PR TITLE
interpolate variables in comments

### LINKED ISSUE #48: Interpolate variables in comments
Hi!

I'm writing a library that generates many classes. I'd like to use [mdcss](https://github.com/jonathantneal/mdcss) to document it, and i'd like to generate the docs in the CSS. I'm using postcss-each & postcss-for to generate class names and values, and I'd like to also generate values in comments, which they rely on postcss-simple-vars for. Here's what I mean:

### input
```
@each $name, $size in (small, med, large), (.5rem, 1rem, 3rem) {
	/*---
		title: Font Size
		section: Typography
		---

		```html
		<span class=".font-$(name)">.font-$(name)</span>
		```
	*/
	.font-$(name),
	.font-$(name) {
		font-size: $(size);
	}
}
```

### output:
```
/*---
	title: Font Size
	section: Typography
	---

	```html
	<span class=".font-small">.font-small</span>
	```
*/
.font-small,
.font-small {
	font-size: .5rem;
}

/*---
	title: Font Size
	section: Typography
	---

	```html
	<span class=".font-med">.font-med</span>
	```
*/
.font-med,
.font-med {
	font-size: 1rem;
}

/*---
	title: Font Size
	section: Typography
	---

	```html
	<span class=".font-large">.font-large</span>
	```
*/
.font-large,
.font-large {
	font-size: 3rem;
}
```

It seems like we would just need to process the comment nodes in addition to other rules. Any interest in adding this feature? PR to follow.

Thanks!

### PR DESCRIPTION
**Pull request by VinSpee**
resolves #48

### CODE REVIEW

**Comment by ai** [comment]
Sorry, I am already in the bed and because this PR seems like not treat important, could I accept it tomorrow.

BTW, why did you need variables in comments? 😊

**Comment by ai** [comment]
Ouh, I found a reason in issue, that your created 😅

**Comment by VinSpee** [comment]
Yes, no big rush or emergency. Thank you and have a good night's sleep!

**Comment by ai** [comment]
Released in 2.0

**Pull request merged**
