### PR TITLE
Variables value to use default entry

### LINKED ISSUE #57: Reset value using webpack?
I have the following css using simple vars:

```css
$brandColor: #8C50FF;

.common {
  color: $brandColor;
  text-decoration: none;
}
```

Now I want to replace the brandColor value in my webpack config, based on the docs I tried:

```javascript
   vars({
		variables: {
			brandColor: '#3e00b6'
		}
    })
```

The actual value remains `#8C50FF`. If I remove the `$brandColor: #8C50FF;` entry, then the value is set.

It would be great to not require the variables to be present always and set a default one instead.

### PR DESCRIPTION
**Pull request by alansouzati**
This PR aims to fix #57.

I've created a defaultVariables object which is used by definition function to check for default values. If present the default value is used, otherwise the css value is maintained.

### CODE REVIEW

**Comment by ai** [comment]
I am not sure, that we need extra options. Seems like it is issue with old one.

**Comment by alansouzati** [comment]
which option you need to add? I can work on it if you want. It seems like you want a flexible behavior to replace the value or not.

In my opinion the replace should be true by default. Anyways, I'm here to help if you are willing to provide guidelines on what you want.

**Comment by ai** [comment]
I'm. Sorry, I misunderstood your PR 😊. Yeap, it looks find.

But I am in the train and could not release new version. So anyway you need to wait 😊.

**Comment by alansouzati** [comment]
You bet no rush. Thanks for being so quick to provide feedback on issues and pull requests.

**Comment by alansouzati** [comment]
hey I don't mean to bug you, but did you have a change to look into this again?

I kind of dependent on this to release a new project in Grommet that uses this library.

**Comment by ai** [comment]
Honesty, you should prepare that me answer will be only in Thursday. Right now I am on the conference on the river 😆.

As temporary solution, you can use your fork. Feel power of modularity.

I understand your pain, but look in my Twitter, and you will understand why I am unavailable 😆 sorry

**Comment by alansouzati** [comment]
cool man, enjoy the music and the river 🎵

**Comment by alansouzati** [comment]
So happy today is Thursday. #feelingHopeful 😆

**Comment by ai** [comment]
Yeap. Thanks for pinging. I try to look today after work.

Sorry for delay :'(

**Comment by alansouzati** [comment]
you bet man, I understand you must be pretty busy. the good news is, the PR is not too big.

**Comment by ai** [comment]
Ouh, I find that you do opposite thing :(. I revert this PR. Let’s continue discuss in issue.

Also always create a test in PR.

**Pull request merged**
